language: ruby
rvm:
  - 1.9.3
  - 2.0.0
services:
  - mongodb
branches:
  only:
    - master
script:
  - RAILS_ENV=test bundle exec rake spec
notifications:
  emails:
    on_success: never
    on_failure: change
